"""Message schema for language models."""

from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field


class TextPart(BaseModel):
    """Text part of a message."""

    type: Literal["text"] = "text"
    text: str


class ToolCallPart(BaseModel):
    """Part of a message representing a tool call request."""

    type: Literal["tool_call"] = "tool_call"
    id: str
    name: str
    arguments: dict[str, Any]


class ToolResultPart(BaseModel):
    """Part of a message representing the result of a tool execution."""

    type: Literal["tool_result"] = "tool_result"
    tool_call_id: str
    content: str


class UserMessage(BaseModel):
    """Message sent by the user."""

    role: Literal["user"] = "user"
    content: list[Annotated[TextPart, Field(discriminator="type")]]


class AssistantMessage(BaseModel):
    """Message generated by the assistant."""

    role: Literal["assistant"] = "assistant"
    content: list[Annotated[TextPart | ToolCallPart, Field(discriminator="type")]]


class ToolMessage(BaseModel):
    """Message containing tool results."""

    role: Literal["tool"] = "tool"
    content: list[ToolResultPart]


Message = Annotated[
    UserMessage | AssistantMessage | ToolMessage, Field(discriminator="role")
]
