"""Message schema for language models."""

import json
from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field


class ToolArgumentsParsingError(Exception):
    """Raised when tool call arguments use an invalid format."""

    def __init__(self, message: str) -> None:
        """Initialize the error with a diagnostic message."""
        super().__init__(message)


def parse_tool_arguments(raw_arguments: str | None) -> dict[str, Any]:
    """Parse raw tool call arguments into a dictionary."""
    stripped_arguments = (raw_arguments or "").strip()
    if not stripped_arguments:
        return {}

    parsed_arguments = json.loads(stripped_arguments)

    if not isinstance(parsed_arguments, dict):
        msg = "JSON parsing did not match to a dictionary format"
        raise ToolArgumentsParsingError(msg)

    return parsed_arguments


class TextPart(BaseModel):
    """Text part of a message."""

    type: Literal["text"] = "text"
    text: str


class ToolCallPart(BaseModel):
    """Part of a message representing a tool call request."""

    type: Literal["tool_call"] = "tool_call"
    id: str
    name: str
    arguments: dict[str, Any]


class ThinkingPart(BaseModel):
    """Part of a message representing the assistant's internal reasoning."""

    type: Literal["thinking"] = "thinking"
    thinking: str


class ToolResultPart(BaseModel):
    """Part of a message representing the result of a tool execution."""

    type: Literal["tool_result"] = "tool_result"
    tool_call_id: str
    content: str


class UserMessage(BaseModel):
    """Message sent by the user."""

    role: Literal["user"] = "user"
    content: list[Annotated[TextPart, Field(discriminator="type")]]


class AssistantMessage(BaseModel):
    """Message generated by the assistant."""

    role: Literal["assistant"] = "assistant"
    content: list[
        Annotated[TextPart | ToolCallPart | ThinkingPart, Field(discriminator="type")]
    ]


class ToolMessage(BaseModel):
    """Message containing tool results."""

    role: Literal["tool"] = "tool"
    content: list[ToolResultPart]


Message = Annotated[
    UserMessage | AssistantMessage | ToolMessage, Field(discriminator="role")
]


class TextDelta(BaseModel):
    """Incremental text chunk from a streaming response."""

    type: Literal["text_delta"] = "text_delta"
    text: str


class ToolCallDelta(BaseModel):
    """Incremental tool call chunk from a streaming response.

    ``arguments_delta`` is a raw JSON string fragment (not a parsed dict).
    """

    type: Literal["tool_call_delta"] = "tool_call_delta"
    id: str
    name: str
    arguments_delta: str


class ThinkingDelta(BaseModel):
    """Incremental thinking chunk from a streaming response."""

    type: Literal["thinking_delta"] = "thinking_delta"
    thinking: str


class AssistantStream(BaseModel):
    """A single chunk from a streaming assistant response.

    Yields incrementally during ``stream_response``. The final
    yield is an ``AssistantMessage`` with the fully accumulated content.
    """

    role: Literal["assistant_stream"] = "assistant_stream"
    content: list[
        Annotated[
            TextDelta | ToolCallDelta | ThinkingDelta, Field(discriminator="type")
        ]
    ]
