"""Message schema for language models."""

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class TextPart(BaseModel):
    """Text part of a message."""

    type: Literal["text"] = "text"
    text: str


class UserMessage(BaseModel):
    """Message sent by the user."""

    role: Literal["user"] = "user"
    content: list[Annotated[TextPart, Field(discriminator="type")]]


class AssistantMessage(BaseModel):
    """Message generated by the assistant."""

    role: Literal["assistant"] = "assistant"
    content: list[Annotated[TextPart, Field(discriminator="type")]]


Message = Annotated[UserMessage | AssistantMessage, Field(discriminator="role")]
